// client
export const BAD_REQUEST = '#400. BAD REQUEST';
export const NOT_FOUND = '#404. RESOURCE NOT FOUND';
export const INVALID_CREDENTIALS = '#401. INVALID CREDENTIALS';
export const INVALID_JWT = '#401. INVALID JWT';
export const INVALID_REFRESH_JWT = '#401. INVALID REFRESH JWT';
export const UNPROCESSABLE_ENTITY = '#422. UNPROCESSABLE ENTITY';
export const INVALID_ID = '#422. INVALID ID TYPE. The id must be of type "string" with length = 12 || 24';
export const INVALID_QUERY_PARAM = '#422. INVALID QUERY PARAMETERS';
export const INVALID_QUERY_TYPE = '#422. INVALID QUERY TYPE';

// server
export const ENV_VARIABLE_UNAVAILABLE = '#500. FAILED TO LOAD ENV VARIABLE';
export const INTERNAL_SERVER_ERROR = '#500. INTERNAL SERVER ERROR';

// database
export const UNABLE_CONNECT_DB = '#503. UNABLE TO CONNECT TO THE DATABASE';
export const UNKNOWN_DB_ERROR = '#500. UNKNOWN DB ERROR';
export const DUPLICATE_KEY_ERROR = '#409. DUPLICATE KEY ERROR';
export const RECORD_NOT_FOUND = '#404. THE REQUESTED RECORD COULD NOT BE FOUND';
