export const BAD_REQUEST = 'BAD REQUEST';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const UNPROCESSABLE_ENTITY = 'UNPROCESSABLE ENTITY';
export const INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR';
