export const BAD_REQUEST = 'BAD REQUEST';
export const NOT_FOUND = 'RESOURCE NOT FOUND';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const UNPROCESSABLE_ENTITY = 'UNPROCESSABLE ENTITY';
export const UNABLE_CONNECT_DB = 'UNABLE TO CONNECT TO THE DATABASE';
export const INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR';
